# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\四六级\可视化\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QApplication
import sys
import random
from PyQt5.QtCore import Qt

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtChart import QChartView,QChart,QLineSeries,QValueAxis, QAreaSeries, QSplineSeries, QPieSeries, QPieSlice
from PyQt5.QtGui import QPainter,QPen,QColor,QLinearGradient
from PyQt5.QtCore import QMargins,QPointF
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.light_num = 5
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(978, 682)
        font = QtGui.QFont()
        font.setPointSize(1)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("background-color: rgb(245, 250, 253);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 211, 761))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.chat = QtWidgets.QPushButton(self.widget)
        self.chat.setGeometry(QtCore.QRect(0, 49, 211, 61))
        self.chat.setFont(font)
        self.chat.setStyleSheet("QPushButton{\n"
"    border:0px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(168, 190, 197);\n"
"text-align:left;\n"
"padding-left:60px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    color :#92bae0;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:checked{\n"
"    background-color: rgb(233, 243, 253);\n"
"color: rgb(119, 159, 220);}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/迅雷云盘/218-chat-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chat.setIcon(icon)
        self.chat.setIconSize(QtCore.QSize(17, 17))
        self.chat.setAutoDefault(True)
        self.chat.setDefault(True)
        self.chat.setFlat(True)
        self.chat.setObjectName("chat")
        self.pronounce = QtWidgets.QPushButton(self.widget)
        self.pronounce.setGeometry(QtCore.QRect(0, 109, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pronounce.setFont(font)
        self.pronounce.setStyleSheet("QPushButton{\n"
"    border:0px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(168, 190, 197);\n"
"text-align:left;\n"
"padding-left:60px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    color :#92bae0;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:checked{\n"
"    background-color: rgb(233, 243, 253);\n"
"color: rgb(119, 159, 220);}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:/迅雷云盘/发音练习.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pronounce.setIcon(icon1)
        self.pronounce.setIconSize(QtCore.QSize(19, 19))
        self.pronounce.setAutoDefault(True)
        self.pronounce.setDefault(True)
        self.pronounce.setFlat(True)
        self.pronounce.setObjectName("pronounce")
        self.Test = QtWidgets.QPushButton(self.widget)
        self.Test.setGeometry(QtCore.QRect(0, 169, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Test.setFont(font)
        self.Test.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Test.setStyleSheet("QPushButton{\n"
"    border:0px;\n"
"\n"
"text-align:left;\n"
"padding-left:60px;\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(168, 190, 197);\n"
"}\n"
"QPushButton:hover{\n"
"    color :#92bae0;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:checked{\n"
"    background-color: rgb(233, 243, 253);\n"
"color: rgb(119, 159, 220);}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:/迅雷云盘/biz-test-o.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Test.setIcon(icon2)
        self.Test.setAutoDefault(True)
        self.Test.setDefault(True)
        self.Test.setFlat(True)
        self.Test.setObjectName("Test")
        self.Identify = QtWidgets.QPushButton(self.widget)
        self.Identify.setGeometry(QtCore.QRect(0, 229, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Identify.setFont(font)
        self.Identify.setStyleSheet("QPushButton{\n"
"    border:0px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(168, 190, 197);\n"
"text-align:left;\n"
"padding-left:60px;\n"
"}\n"
"QPushButton:hover{\n"
"    color :#92bae0;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:checked{\n"
"    background-color: rgb(233, 243, 253);\n"
"color: rgb(119, 159, 220);}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("D:/迅雷云盘/人工智能.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Identify.setIcon(icon3)
        self.Identify.setIconSize(QtCore.QSize(23, 23))
        self.Identify.setAutoDefault(True)
        self.Identify.setDefault(True)
        self.Identify.setFlat(True)
        self.Identify.setObjectName("Identify")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 500, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_5.setStyleSheet("border:0px;\n"
"color: rgb(168, 190, 197);\n"
"text-align:left;\n"
"padding-left:60px;\n"
"cursor:true;\n"
"change-cursor: cursor(\'PointingHand\');")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("D:/迅雷云盘/设置.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_5.setAutoDefault(True)
        self.pushButton_5.setDefault(True)
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setGeometry(QtCore.QRect(0, 560, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("border:0px;\n"
"color: rgb(168, 190, 197);\n"
"text-align:left;\n"
"padding-left:60px;\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("D:/迅雷云盘/产品介绍@1x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon5)
        self.pushButton_6.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 620, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_7.setStyleSheet("border:0px;\n"
"color: rgb(168, 190, 197);\n"
"text-align:left;\n"
"padding-left:60px;")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("D:/迅雷云盘/退出.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon6)
        self.pushButton_7.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_7.setObjectName("pushButton_7")
        self.data = QtWidgets.QPushButton(self.widget)
        self.data.setGeometry(QtCore.QRect(0, 290, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.data.setFont(font)
        self.data.setStyleSheet("color: rgb(119, 159, 220);\n"
"    border:0px;\n"
"    background-color: rgb(233, 243, 253);\n"
"text-align:left;\n"
"padding-left:60px;\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("D:/迅雷云盘/数据统计.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.data.setIcon(icon7)
        self.data.setIconSize(QtCore.QSize(20, 20))
        self.data.setAutoDefault(True)
        self.data.setDefault(True)
        self.data.setFlat(True)
        self.data.setObjectName("data")
        self.label_18 = QtWidgets.QLabel(self.widget)
        self.label_18.setGeometry(QtCore.QRect(90, 10, 72, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: #779fdc;")
        self.label_18.setObjectName("label_18")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 5, 41, 41))
        self.pushButton_2.setStyleSheet("border:0px;")
        self.pushButton_2.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("D:/迅雷云盘/多语言.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon8)
        self.pushButton_2.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_2.setAutoDefault(True)
        self.pushButton_2.setDefault(True)
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(210, 0, 771, 681))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.textEdit = QtWidgets.QTextEdit(self.page_3)
        self.textEdit.setGeometry(QtCore.QRect(60, 610, 631, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("border:1px solid #779fdc;\n"
"border-radius:15px;\n"
"line-height:41px;\n"
"color:#8b9fdc;")
        self.textEdit.setLineWidth(1)
        self.textEdit.setObjectName("textEdit")
        self.widget_chat = QtWidgets.QWidget(self.page_3)
        self.widget_chat.setGeometry(QtCore.QRect(0, 0, 771, 601))
        self.widget_chat.setObjectName('widget_chat')
        self.scroll_area = QtWidgets.QScrollArea()
        self.scroll_layout = QtWidgets.QVBoxLayout(self.widget_chat)
        for i in range(2):
            l = QtWidgets.QLabel()
            l.setText(str(i))
            self.scroll_layout.addWidget(l)
        self.scroll_area.setWidget(self.widget_chat)
        self.scroll_area.setWidgetResizable(True)
        self.label_4 = QtWidgets.QLabel(self.widget_chat)
        self.scroll_layout.addWidget(self.label_4)
        self.label_4.setGeometry(QtCore.QRect(130, 190, 491, 141))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(65)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgba(119, 159, 220, 100);\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget_chat)
        self.label_5.setGeometry(QtCore.QRect(220, 310, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgba(119, 159, 220, 100);")
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.page_3)
        self.pushButton.setGeometry(QtCore.QRect(650, 620, 31, 31))
        self.pushButton.setStyleSheet("border:0px;\n"
"background-color: ;\n"
"color: rgb(221, 231, 240);")
        self.pushButton.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("D:/迅雷云盘/发送.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon9)
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setAutoDefault(True)
        self.pushButton.setDefault(True)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget.addWidget(self.page_4)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.page)
        self.stackedWidget_2.setGeometry(QtCore.QRect(0, 10, 771, 651))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.widget_4 = QtWidgets.QWidget(self.page_7)
        self.widget_4.setGeometry(QtCore.QRect(40, 12, 561, 101))
        self.widget_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:30px;")
        self.widget_4.setObjectName("widget_4")
        self.label_14 = QtWidgets.QLabel(self.widget_4)
        self.label_14.setGeometry(QtCore.QRect(20, 20, 72, 15))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color:rgb(117, 117, 117);")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.widget_4)
        self.label_15.setGeometry(QtCore.QRect(20, 37, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.widget_4)
        self.label_16.setGeometry(QtCore.QRect(88, 48, 72, 15))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.pushButton_14 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_14.setGeometry(QtCore.QRect(430, 3, 111, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("border:0px;\n"
"color: rgb(119, 159, 220);")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("D:/迅雷云盘/历史数据.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_14.setIcon(icon10)
        self.pushButton_14.setAutoDefault(True)
        self.pushButton_14.setDefault(True)
        self.pushButton_14.setFlat(True)
        self.pushButton_14.setObjectName("pushButton_14")
        self.progressBar_3 = QtWidgets.QProgressBar(self.widget_4)
        self.progressBar_3.setGeometry(QtCore.QRect(20, 70, 521, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(233, 243, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 243, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 243, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 137, 250, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 243, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 243, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 243, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 137, 250, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 243, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 243, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 243, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 137, 250, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.progressBar_3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.progressBar_3.setFont(font)
        self.progressBar_3.setAutoFillBackground(False)
        self.progressBar_3.setStyleSheet("background-color: #e9f3fd;\n"
"border-radius:4px;")
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setTextVisible(False)
        self.progressBar_3.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_3.setObjectName("progressBar_3")
        self.label_17 = QtWidgets.QLabel(self.page_7)
        self.label_17.setGeometry(QtCore.QRect(620, 30, 41, 21))
        font = QtGui.QFont()
        font.setFamily("方正黑体_GBK")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.comboBox_5 = QtWidgets.QComboBox(self.page_7)
        self.comboBox_5.setGeometry(QtCore.QRect(670, 30, 87, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.stackedWidget_2.addWidget(self.page_7)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.widget_3 = QtWidgets.QWidget(self.page_6)
        self.widget_3.setGeometry(QtCore.QRect(40, 12, 561, 101))
        self.widget_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:30px;")
        self.widget_3.setObjectName("widget_3")
        self.label_10 = QtWidgets.QLabel(self.widget_3)
        self.label_10.setGeometry(QtCore.QRect(20, 20, 72, 15))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:rgb(117, 117, 117);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.widget_3)
        self.label_11.setGeometry(QtCore.QRect(20, 37, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.widget_3)
        self.label_12.setGeometry(QtCore.QRect(88, 48, 72, 15))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_13.setGeometry(QtCore.QRect(430, 3, 111, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("border:0px;\n"
"color: rgb(119, 159, 220);")
        self.pushButton_13.setIcon(icon10)
        self.pushButton_13.setAutoDefault(True)
        self.pushButton_13.setDefault(True)
        self.pushButton_13.setFlat(True)
        self.pushButton_13.setObjectName("pushButton_13")
        self.progressBar_2 = QtWidgets.QProgressBar(self.widget_3)
        self.progressBar_2.setGeometry(QtCore.QRect(20, 70, 521, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(233, 243, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 243, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 243, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 137, 250, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 243, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 243, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 243, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 137, 250, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 243, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 243, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 243, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 137, 250, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.progressBar_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.progressBar_2.setFont(font)
        self.progressBar_2.setAutoFillBackground(False)
        self.progressBar_2.setStyleSheet("background-color: #e9f3fd;\n"
"border-radius:4px;")
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setTextVisible(False)
        self.progressBar_2.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_2.setObjectName("progressBar_2")
        self.comboBox_4 = QtWidgets.QComboBox(self.page_6)
        self.comboBox_4.setGeometry(QtCore.QRect(670, 30, 87, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label_13 = QtWidgets.QLabel(self.page_6)
        self.label_13.setGeometry(QtCore.QRect(620, 30, 41, 21))
        font = QtGui.QFont()
        font.setFamily("方正黑体_GBK")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.stackedWidget_2.addWidget(self.page_6)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.widget_2 = QtWidgets.QWidget(self.page_8)
        self.widget_2.setGeometry(QtCore.QRect(40, 12, 561, 101))
        self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:30px;")
        self.widget_2.setObjectName("widget_2")
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 72, 15))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgb(117, 117, 117);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setGeometry(QtCore.QRect(20, 37, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget_2)
        self.label_8.setGeometry(QtCore.QRect(88, 48, 72, 15))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.pushButton_12 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_12.setGeometry(QtCore.QRect(430, 3, 111, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("border:0px;\n"
"color: rgb(119, 159, 220);")
        self.pushButton_12.setIcon(icon10)
        self.pushButton_12.setAutoDefault(True)
        self.pushButton_12.setDefault(True)
        self.pushButton_12.setFlat(True)
        self.pushButton_12.setObjectName("pushButton_12")
        self.progressBar = QtWidgets.QProgressBar(self.widget_2)
        self.progressBar.setGeometry(QtCore.QRect(20, 70, 521, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(233, 243, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 243, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 243, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 137, 250, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 243, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 243, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 243, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 137, 250, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 243, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 243, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 243, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 137, 250, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.progressBar.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.progressBar.setFont(font)
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setStyleSheet("background-color: #e9f3fd;\n"
"border-radius:4px;")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.comboBox_3 = QtWidgets.QComboBox(self.page_8)
        self.comboBox_3.setGeometry(QtCore.QRect(670, 30, 87, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_9 = QtWidgets.QLabel(self.page_8)
        self.label_9.setGeometry(QtCore.QRect(620, 30, 41, 21))
        font = QtGui.QFont()
        font.setFamily("方正黑体_GBK")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.stackedWidget_2.addWidget(self.page_8)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.comboBox = QtWidgets.QComboBox(self.page_5)
        self.comboBox.setGeometry(QtCore.QRect(110, 88, 81, 22))
        font = QtGui.QFont()
        font.setFamily("方正黑体_GBK")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QComboBox {\n"
"    color:#305974;\n"
"    border: 0px solid #f3f3f3;/*设置线宽*/\n"
"    background-color: #f5fafd;/*背景颜色*/\n"
"    padding: 1px 2px 1px 2px;  /*针对于组合框中的文本内容*/\n"
"    text-align:bottom;\n"
"    /*min-height: 5em;*/\n"
"}/*QCombobox右侧按钮*/\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;/*放于右方顶部*/\n"
"     /*border-radius: 15px;\n"
"    border-left-width: 1px;\n"
"    border-left-style: solid;*/\n"
"/*padding-right: 50px;*/\n"
"    border-left-color: darkgray;\n"
"\n"
"}\n"
"/*QCombobox右侧按钮的箭头图标*/\n"
"QComboBox::down-arrow {\n"
"    width: 10px;/*设置该图标的宽高*/\n"
"    height: 10px;\n"
"}\n"
"")
        self.widget_5 = QtWidgets.QWidget(self.page_5)
        self.widget_5.setGeometry(QtCore.QRect(40, 360, 331, 311))
        self.widget_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "border-radius:10%;")
        self.widget_5.setObjectName("widget_5")
        self.label_19 = QtWidgets.QLabel(self.widget_5)
        self.label_19.setGeometry(QtCore.QRect(80, 4, 161, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.widget_5)
        self.label_20.setGeometry(QtCore.QRect(0, 40, 331, 16))
        self.label_20.setStyleSheet("border-top:1px solid #000000;")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.widget_5)
        self.label_21.setGeometry(QtCore.QRect(10, 60, 251, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.widget_5)
        self.label_22.setGeometry(QtCore.QRect(250, 50, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: rgb(255, 170, 0);")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.widget_5)
        self.label_23.setGeometry(QtCore.QRect(10, 90, 72, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.widget_5)
        self.label_24.setGeometry(QtCore.QRect(140, 90, 72, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_26 = QtWidgets.QLabel(self.widget_5)
        self.label_26.setGeometry(QtCore.QRect(10, 120, 72, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.widget_5)
        self.label_27.setGeometry(QtCore.QRect(10, 160, 72, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.widget_5)
        self.label_28.setGeometry(QtCore.QRect(10, 200, 191, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_30 = QtWidgets.QLabel(self.widget_5)
        self.label_30.setGeometry(QtCore.QRect(290, 60, 21, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_25 = QtWidgets.QLabel(self.widget_5)
        self.label_25.setGeometry(QtCore.QRect(90, 80, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: rgb(255, 170, 0);")
        self.label_25.setObjectName("label_25")
        self.label_31 = QtWidgets.QLabel(self.widget_5)
        self.label_31.setGeometry(QtCore.QRect(80, 120, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color: rgb(255, 170, 0);")
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.widget_5)
        self.label_32.setGeometry(QtCore.QRect(130, 130, 21, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.widget_5)
        self.label_33.setGeometry(QtCore.QRect(80, 160, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("color: rgb(255, 170, 0);")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.widget_5)
        self.label_34.setGeometry(QtCore.QRect(130, 170, 21, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.widget_5)
        self.label_35.setGeometry(QtCore.QRect(200, 200, 121, 31))
        font = QtGui.QFont()
        font.setFamily("方正黑体_GBK")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color: rgb(74, 148, 110);")
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.widget_5)
        self.label_36.setGeometry(QtCore.QRect(10, 240, 191, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.widget_5)
        self.label_37.setGeometry(QtCore.QRect(170, 240, 121, 31))
        font = QtGui.QFont()
        font.setFamily("方正黑体_GBK")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("color: rgb(74, 148, 110);")
        self.label_37.setObjectName("label_37")
        self.label_20.raise_()
        self.label_19.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.label_26.raise_()
        self.label_27.raise_()
        self.label_28.raise_()
        self.label_30.raise_()
        self.label_25.raise_()
        self.label_31.raise_()
        self.label_32.raise_()
        self.label_33.raise_()
        self.label_34.raise_()
        self.label_35.raise_()
        self.label_36.raise_()
        self.label_37.raise_()
        self.comboBox.setEditable(False)
        self.comboBox.setDuplicatesEnabled(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.page_5)
        self.label_2.setGeometry(QtCore.QRect(650, 40, 51, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(48, 89, 116);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.page_5)
        self.label_3.setGeometry(QtCore.QRect(30, 90, 51, 16))
        font = QtGui.QFont()
        font.setFamily("方正黑体_GBK")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(146, 165, 171);")
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.page_5)
        self.label.setGeometry(QtCore.QRect(30, 30, 191, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(48, 89, 116);")
        self.label.setObjectName("label")
        self.pushButton_9 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_9.setGeometry(QtCore.QRect(570, 20, 61, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("border-radius:30%;\n"
"background-image: url(C:/Users/小冠/Pictures/微信图片_20220415132255.jpg);")
        self.pushButton_9.setText("")
        self.pushButton_9.setAutoDefault(True)
        self.pushButton_9.setDefault(True)
        self.pushButton_9.setFlat(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_8 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_8.setGeometry(QtCore.QRect(520, 40, 25, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(5)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.pushButton_8.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("D:/迅雷云盘/通知.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon11)
        self.pushButton_8.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_8.setAutoDefault(True)
        self.pushButton_8.setDefault(True)
        self.pushButton_8.setFlat(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_11 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_11.setGeometry(QtCore.QRect(80, 84, 31, 28))
        self.pushButton_11.setStyleSheet("border:0px;")
        self.pushButton_11.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("D:/迅雷云盘/日期.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon12)
        self.pushButton_11.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_11.setAutoDefault(True)
        self.pushButton_11.setDefault(True)
        self.pushButton_11.setFlat(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.stackedWidget.addWidget(self.page_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.chat.clicked.connect(self.chat_)
        self.pronounce.clicked.connect(self.pronounce_)
        self.Test.clicked.connect(self.Test_)
        self.Identify.clicked.connect(self.identify_)
        self.data.clicked.connect(self.data_)
        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(4)
        self.stackedWidget_2.setCurrentIndex(0)
        pen = QPen()
        pen.setColor(QColor('#8fb7ea'))
        pen.setWidth(1)
        font_ = QtGui.QFont()
        font_.setPointSize(6)
        font_.setFamily('Arial')
        self.chart = QChart()  # 创建chart
        self.chartview = QChartView(self.page_5)  # 创建视图
        self.chartview.setGeometry(20, 110, 730, 250)
        self.series = QSplineSeries()  # 曲线序列
        self.series.setPen(pen)
        self.series.setPointLabelsVisible(False)
        self.series.setPointsVisible(True)
        self.chart.setFont(font_)
        self.chart.setMinimumSize(700, 220)
        background_brush = QtGui.QBrush(QColor(254, 255, 255,alpha=0))
        self.chart.setMargins(QMargins(0,-30,0,0))
        self.chart.setBackgroundBrush(background_brush)
        self.chartview.setStyleSheet('color:#92a5ab;')
        self.chartview.setRenderHint(QPainter.Antialiasing)
        self.chartview.setChart(self.chart)
        self.series_2 = QSplineSeries()  # 曲线序列
        self.series.setPointLabelsVisible(False)
        self.series_2.setPointsVisible(True)
        self.pushButton.clicked.connect(self.send_data)
        self.draw_day()
        # 创建饼图系列
        self.pie_series = QPieSeries()
        # 添加饼图切片
        slice1 = QPieSlice("匹配题", 42)
        slice2 = QPieSlice("选词填空", 28)
        slice3 = QPieSlice("翻译", 14)

        # 将切片添加到系列中
        self.pie_series.append(slice1)
        self.pie_series.append(slice2)
        self.pie_series.append(slice3)

        # 创建图表并将系列添加到图表中
        self.chart_2 = QChart()
        self.chart_2.addSeries(self.pie_series)
        self.chart_2.setTitle("Percentage of completed questions")
        self.chart_2.setFont(font_)
        self.chart_2.setMinimumSize(331, 331)
        background_brush = QtGui.QBrush(QColor(254, 255, 255, alpha=0))
        self.chart_2.setMargins(QMargins(0, -30, 0, 0))
        self.chart_2.setBackgroundBrush(background_brush)
        # 创建图表视图并设置图表
        self.chart_view = QChartView(self.page_5)
        self.chart_view.setRenderHint(QPainter.Antialiasing)
        self.chart_view.setGeometry(400, 360, 331, 311)
        self.chart_view.setStyleSheet('color:#92a5ab;')
        self.chart_view.setRenderHint(QPainter.Antialiasing)
        self.chart_view.setChart(self.chart_2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.chat.setText(_translate("MainWindow", "  Chat"))
        self.pronounce.setText(_translate("MainWindow", "  Pronounce"))
        self.Test.setText(_translate("MainWindow", "  Test"))
        self.Identify.setText(_translate("MainWindow", "  Identify"))
        self.pushButton_5.setText(_translate("MainWindow", "  Settings"))
        self.pushButton_6.setText(_translate("MainWindow", "  Introduction"))
        self.pushButton_7.setText(_translate("MainWindow", "  Logout"))
        self.data.setText(_translate("MainWindow", "  Data"))
        self.label_18.setText(_translate("MainWindow", "语智"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "Dialogue or question"))
        self.label_4.setText(_translate("MainWindow", "语智未来"))
        self.label_5.setText(_translate("MainWindow", "Oral English intelligent tutor"))
        self.label_14.setText(_translate("MainWindow", "今日学习"))
        self.label_15.setText(_translate("MainWindow", "00分钟"))
        self.label_16.setText(_translate("MainWindow", "/60分钟"))
        self.pushButton_14.setText(_translate("MainWindow", "我的学习曲线"))
        self.progressBar_3.setFormat(_translate("MainWindow", "p%"))
        self.label_17.setText(_translate("MainWindow", "大学"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "四级"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "雅思"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "托福"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "六级"))
        self.label_10.setText(_translate("MainWindow", "今日学习"))
        self.label_11.setText(_translate("MainWindow", "00分钟"))
        self.label_12.setText(_translate("MainWindow", "/60分钟"))
        self.pushButton_13.setText(_translate("MainWindow", "我的学习曲线"))
        self.progressBar_2.setFormat(_translate("MainWindow", "p%"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "听力"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "阅读理解"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "七选五"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "完形填空"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "语法填空"))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "短文改错"))
        self.label_13.setText(_translate("MainWindow", "高中"))
        self.label_6.setText(_translate("MainWindow", "今日学习"))
        self.label_7.setText(_translate("MainWindow", "00分钟"))
        self.label_8.setText(_translate("MainWindow", "/60分钟"))
        self.pushButton_12.setText(_translate("MainWindow", "我的学习曲线"))
        self.progressBar.setFormat(_translate("MainWindow", "p%"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "听力"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "单项选择"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "句子翻译"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "完形填空"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "补全对话"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "阅读理解"))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "句意填词"))
        self.label_9.setText(_translate("MainWindow", "初中"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Day"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Month"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Year"))
        self.label_2.setText(_translate("MainWindow", "Log in"))
        self.label_3.setText(_translate("MainWindow", "Show:"))
        self.label.setText(_translate("MainWindow", "Learning Curve"))

        self.label_19.setText(_translate("MainWindow", "Learning data"))
        self.label_21.setText(_translate("MainWindow", "截至目前为止，你的学习进度为"))
        self.label_22.setText(_translate("MainWindow", "0.1"))
        self.label_23.setText(_translate("MainWindow", "累计做题"))
        self.label_24.setText(_translate("MainWindow", "道"))
        self.label_26.setText(_translate("MainWindow", "正确率"))
        self.label_27.setText(_translate("MainWindow", "错误率"))
        self.label_28.setText(_translate("MainWindow", "错误率最高的题目类型为"))
        self.label_30.setText(_translate("MainWindow", "%"))
        self.label_25.setText(_translate("MainWindow", " 14"))
        self.label_31.setText(_translate("MainWindow", " 70"))
        self.label_32.setText(_translate("MainWindow", "%"))
        self.label_33.setText(_translate("MainWindow", " 10"))
        self.label_34.setText(_translate("MainWindow", "%"))
        self.label_35.setText(_translate("MainWindow", "匹配题"))
        self.label_36.setText(_translate("MainWindow", "练习题目最多类型为"))
        self.label_37.setText(_translate("MainWindow", "匹配题"))

    def chat_(self):
        if self.light_num == 1:
            return
        self.chat.setStyleSheet("QPushButton{"
                                "    border:0px;\n"
                                "text-align:left;\n"
                                "padding-left:60px;"
                                "background-color: rgb(233, 243, 253);color: rgb(119, 159, 220);}")
        self.refresh_button()
        self.stackedWidget.setCurrentIndex(0)
        self.light_num = 1

    def pronounce_(self):
        if self.light_num == 2:
            return
        self.pronounce.setStyleSheet("QPushButton{"
                            "    border:0px;\n"
                            "text-align:left;\n"
                            "padding-left:60px;"
                            "background-color: rgb(233, 243, 253);color: rgb(119, 159, 220);}")
        self.refresh_button()
        self.stackedWidget.setCurrentIndex(3)
        self.light_num = 2

    def Test_(self):
        if self.light_num == 3:
            return
        self.Test.setStyleSheet("QPushButton{"
                                 "    border:0px;\n"
                                 "text-align:left;\n"
                                 "padding-left:60px;"
                                 "background-color: rgb(233, 243, 253);color: rgb(119, 159, 220);}")
        self.stackedWidget.setCurrentIndex(2)
        self.refresh_button()
        self.light_num = 3

    def identify_(self):
        if self.light_num == 4:
            return
        self.Identify.setStyleSheet("QPushButton{"
                                         "    border:0px;\n"
                                         "text-align:left;\n"
                                         "padding-left:60px;"
                                         "background-color: rgb(233, 243, 253);color: rgb(119, 159, 220);}")
        self.refresh_button()
        self.stackedWidget.setCurrentIndex(1)
        self.light_num = 4

    def data_(self):
        if self.light_num == 5:
            return
        self.data.setStyleSheet("QPushButton{"
                                         "    border:0px;\n"
                                         "text-align:left;\n"
                                         "padding-left:60px;"
                                         "background-color: rgb(233, 243, 253);color: rgb(119, 159, 220);}")
        self.refresh_button()
        self.stackedWidget.setCurrentIndex(4)
        self.light_num = 5

    def refresh_button(self):
        if self.light_num == 1:
            self.chat.setStyleSheet("QPushButton{\n"
        "    border:0px;\n"
        "    background-color: rgb(255, 255, 255);\n"
        "    color: rgb(168, 190, 197);\n"
        "text-align:left;\n"
        "padding-left:60px;\n"
        "\n"
        "}\n"
        "QPushButton:hover{\n"
        "    color :#92bae0;\n"
        "    background-color: rgb(255, 255, 255);\n"
        "}\n"
        "QPushButton:checked{\n"
        "    background-color: rgb(233, 243, 253);\n"
        "color: rgb(119, 159, 220);}")
        elif self.light_num == 2:
            self.pronounce.setStyleSheet("QPushButton{\n"
        "    border:0px;\n"
        "    background-color: rgb(255, 255, 255);\n"
        "    color: rgb(168, 190, 197);\n"
        "text-align:left;\n"
        "padding-left:60px;\n"
        "\n"
        "}\n"
        "QPushButton:hover{\n"
        "    color :#92bae0;\n"
        "    background-color: rgb(255, 255, 255);\n"
        "}\n"
        "QPushButton:checked{\n"
        "    background-color: rgb(233, 243, 253);\n"
        "color: rgb(119, 159, 220);}")
        elif self.light_num == 3:
            self.Test.setStyleSheet("QPushButton{\n"
        "    border:0px;\n"
        "    background-color: rgb(255, 255, 255);\n"
        "    color: rgb(168, 190, 197);\n"
        "text-align:left;\n"
        "padding-left:60px;\n"
        "\n"
        "}\n"
        "QPushButton:hover{\n"
        "    color :#92bae0;\n"
        "    background-color: rgb(255, 255, 255);\n"
        "}\n"
        "QPushButton:checked{\n"
        "    background-color: rgb(233, 243, 253);\n"
        "color: rgb(119, 159, 220);}")
        elif self.light_num == 4:
            self.Identify.setStyleSheet("QPushButton{\n"
        "    border:0px;\n"
        "    background-color: rgb(255, 255, 255);\n"
        "    color: rgb(168, 190, 197);\n"
        "text-align:left;\n"
        "padding-left:60px;\n"
        "\n"
        "}\n"
        "QPushButton:hover{\n"
        "    color :#92bae0;\n"
        "    background-color: rgb(255, 255, 255);\n"
        "}\n"
        "QPushButton:checked{\n"
        "    background-color: rgb(233, 243, 253);\n"
        "color: rgb(119, 159, 220);}")
        elif self.light_num == 5:
            self.data.setStyleSheet("QPushButton{\n"
        "    border:0px;\n"
        "    background-color: rgb(255, 255, 255);\n"
        "    color: rgb(168, 190, 197);\n"
        "text-align:left;\n"
        "padding-left:60px;\n"
        "\n"
        "}\n"
        "QPushButton:hover{\n"
        "    color :#92bae0;\n"
        "    background-color: rgb(255, 255, 255);\n"
        "}\n"
        "QPushButton:checked{\n"
        "    background-color: rgb(233, 243, 253);\n"
        "color: rgb(119, 159, 220);}")

    def draw_day(self):
        # 添加数值
        font_ = QtGui.QFont()
        font_.setBold(True)
        font_.setPointSize(8)
        for i in range(23):
            if i != 17 and i != 12:
                self.series.append(i, 0)
            elif i == 17:
                self.series.append(i, 16)
            elif i == 12:
                self.series.append(i, 40)
            self.series_2.append(i,0)
        axisX = QValueAxis() #x轴
        axisX.setRange(0, 24) # 设置范围
        axisX.setTickCount(6)
        axisX.setMinorTickCount(3)
        axisX.setLineVisible(False)
        axisX.setMinorGridLineVisible(False)
        axisX.setGridLineVisible(False)
        axisX.setLabelFormat('%d')
        axisX.setLabelsColor(QColor(170, 176, 187, 200))
        axisX.setLabelsFont(font_)
        axisY = QValueAxis()
        axisY.setTickCount(4)
        axisY.setMinorTickCount(1)
        axisY.setRange(0, 60)
        axisY.setLabelFormat('%d')
        axisY.setLinePenColor(QColor(0,0,0,0))
        axisY.setLineVisible(False)
        axisY.setLabelFormat('%d')
        axisY.setLabelsColor(QColor(170, 176, 187, 200))
        axisY.setLabelsFont(font_)
        self.area_series = QAreaSeries(self.series, self.series_2)
        area_brush = QColor(125, 169, 229, 70)
        gradient = QLinearGradient(QPointF(0,0), QPointF(0, 1))
        gradient.setColorAt(1.0, area_brush)
        gradient.setColorAt(0.0, QColor(125, 169, 229, 150))
        gradient.setCoordinateMode(QLinearGradient.ObjectBoundingMode)
        self.area_series.setBrush(gradient)
        self.chart.addSeries(self.area_series)
        self.chart.setAxisX(axisX, self.series)
        self.chart.setAxisY(axisY, self.series)
        self.legendMarkers = self.chart.legend().markers()
        self.legendMarkers[0].setVisible(False)

    def send_data(self):
        content = self.textEdit.toPlainText()
        self.textEdit.setPlainText('')
        # self.
if __name__ == "__main__":
    app = QApplication([])

    # 此处调用GUI的程序
    widgets = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(widgets)
    widgets.show()
    # 结束

    sys.exit(app.exec_())